export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

      <div className="prose prose-lg max-w-none space-y-6">
        <section>
          <h2 className="text-2xl font-bold mb-3">1. Overview</h2>
          <p className="text-gray-700">
            SNACC PARI (Student Nutrition Access & Care Perception for Adolescent
            Risk Index) is an anonymous, voluntary screening tool designed to help
            understand nutritional challenges in schools. This privacy policy
            explains how we collect and use your data.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">2. What Data We Collect</h2>
          <p className="text-gray-700">The survey collects the following types of data:</p>
          <ul className="list-disc list-inside text-gray-700 mt-2 space-y-1">
            <li>
              <strong>Demographic Information:</strong> Age, grade, sex, school name
            </li>
            <li>
              <strong>Anthropometry:</strong> Height and weight (with optional flag for measured data)
            </li>
            <li>
              <strong>Dietary Information:</strong> Frequency of consumption of various food groups
            </li>
            <li>
              <strong>Economic Access:</strong> Food cost barriers, meal frequency, school meal usage
            </li>
            <li>
              <strong>Knowledge & Awareness:</strong> Understanding of protein and balanced diet
            </li>
            <li>
              <strong>Structural Barriers:</strong> Food availability and market access
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">3. How We Use Your Data</h2>
          <p className="text-gray-700">Your responses are used to:</p>
          <ul className="list-disc list-inside text-gray-700 mt-2 space-y-1">
            <li>Calculate your individual risk score (for your own awareness)</li>
            <li>Identify aggregate trends and patterns in nutrition access</li>
            <li>Generate anonymized statistics for research and school planning</li>
            <li>Inform school feeding and nutrition programs</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">4. Data Anonymity & Storage</h2>
          <p className="text-gray-700">
            <strong>Anonymous Submission:</strong> You can complete the survey without
            providing your name or identifying information. A unique code (SGIC) is
            optional and used only for school coordination purposes.
          </p>
          <p className="text-gray-700 mt-3">
            <strong>Data Storage:</strong> All responses are stored securely in CSV files
            and optionally backed up to Google Sheets. Data is encrypted in transit
            (HTTPS) and at rest.
          </p>
          <p className="text-gray-700 mt-3">
            <strong>Retention:</strong> Data is retained indefinitely for longitudinal
            research, but is never used for individual identification or personal contact.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">5. Who Has Access?</h2>
          <p className="text-gray-700">
            Only authorized school coordinators with valid login credentials can access
            the admin dashboard to view data. Individual responses are not shared with
            third parties without explicit consent.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">6. Your Rights</h2>
          <p className="text-gray-700">
            Since responses are anonymous, we cannot identify your individual response
            after submission. If you have concerns about your data, please contact the
            school coordinator.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">7. Disclaimer</h2>
          <p className="text-gray-700">
            <strong>This is NOT a clinical diagnostic tool.</strong> The risk score
            generated by this survey is for informational and research purposes only and
            should not be used as a substitute for professional medical evaluation. Always
            consult with a healthcare provider for medical concerns.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">8. Contact</h2>
          <p className="text-gray-700">
            For questions about this privacy policy or your data, please contact your
            school coordinator or visit our dashboard for more information.
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-gray-200">
        <p className="text-sm text-gray-600">
          Last updated: September 2026 | Version 2.0
        </p>
      </div>
    </div>
  );
}
